### ISSUE TITLE
TypeConverter Error

### ISSUE THREAD

**Issue by Gaborboy95** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1557]
Hello! I used the wiki page getting started with
`<materialDesign:BundledTheme BaseTheme="Dark" PrimaryColor="DarkPuple" SecondaryColor="Lime" />`
And it seems to have the next error:
![image](https://user-images.githubusercontent.com/30007117/70865376-35028a80-1f5d-11ea-849e-53f1dd557722.png)
This also applies to AccentColor.

Sorry for not providing a repo, this is just a quick thing.

**Comment by Keboo** [comment]
Hi @Gaborboy95 which version of the library are you on? There was a similar issue in 2.60 that is fixed in the 3.0.0 release

**Comment by Gaborboy95** [comment]
I am using the 3.0.0 release as far as i'm concerned, at least that's what nuget says

**Comment by MichelMichels** [comment]
@Gaborboy95 I see from your screenshot that you wrote "DarkPuple", the correct color should be "DeepPurple". Does this fix your issue?

**Comment by Gaborboy95** [comment]
Sadly, no. Still the same error
![image](https://user-images.githubusercontent.com/30007117/70911492-4e194300-2012-11ea-90b3-9ec77aab61df.png)

**Comment by MichelMichels** [comment]
Could you copy your Application.Resources here? Are you using this in a .NET Core or Framework application?

**Comment by Gaborboy95** [comment]
I am using it in a .net core 3.0 application
` <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>

                <materialDesign:BundledTheme
                    BaseTheme="Dark"
                    PrimaryColor="DeepPurple"
                    SecondaryColor="Lime" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />

            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>`

**Comment by MichelMichels** [comment]
Could you create a test repo to showcase the error? I can't replicate your error

**Comment by Gaborboy95** [comment]
https://github.com/Gaborboy95/CukiKaveManagerV2

**Comment by Gaborboy95** [comment]
The application cannot be built because of the error

**Comment by MichelMichels** [comment]
You didn't include the .sln file in your repository and the code is incomplete. After adding my own .sln file, I can build your project, but there is no code in that repository that references this project.

**Comment by hiroppp** [comment]
I had the same problem.
Solved by NuGet package (Install-Package **MaterialDesignColors**).

**Comment by Gaborboy95** [comment]
Thank you! It works!
