### ISSUE TITLE
Validation decorators overlay dialog

### ISSUE THREAD

**Issue by RobSmyth** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2112]
Hi,

When I create a dialog from a a DialogHost, and the dialog overlays an area of the application, that launched the dialog, that is showing validation errors, the decorators (red underlines) show up clearly on by dialog. It appears that are on a layer above the dialog. If I change the DialogHost to be a portion of the UI that does not display validation errors, all is good.

Known issue?

Details:

- MaterialDesignExtensions 3.2.0
- MaterialDesignThemes 3.1.3
- Using dark theme

**Comment by CorradoBarbero** [comment]
Same here, see pictures before and after running the dialog, the validation error does not get "opaqued":
![2020-10-08_160255](https://user-images.githubusercontent.com/62978436/95469475-fc1a2300-097f-11eb-908e-4a83a3b6ba9c.jpg)
![2020-10-08_160313](https://user-images.githubusercontent.com/62978436/95469478-fde3e680-097f-11eb-8cfb-a3e7fbe8c8ce.jpg)

**Comment by Keboo** [comment]
There was an issue with adorners that was addressed in the 3.2.0 release. Can you update to the 3.2.0 and see if that resolves the issue?

**Comment by CorradoBarbero** [comment]
My screenshots were from 3.2.0 already...

**Comment by Keboo** [comment]
Ah this is likely caused by using the popup for the validation rather than the inline one. Those darkened overlays are done within the current visual tree, while popups are lightweight windows and will show on top of anything in the current window. 
There is a `ValidationAssistn.UsePopup` attached property you can set to `false` that will cause the validation to show within the current visual tree, rather than using a popup.

**Comment by CorradoBarbero** [comment]
Thanks, the workaround worked perfectly!

**Comment by RobSmyth** [comment]
Hi,

Apologies for my slow response. The issue remains from me using 3.2.0 and `ValidationAssist.UsePopup`. The image blow show the dialog on the left with the validation lines from the window behind.

![image](https://user-images.githubusercontent.com/6183736/97095809-ddba6400-16af-11eb-9350-29aa9d6d1e94.png)

The control generating the validation is:

```
 <TextBox
            Text="{Binding Value.StringValue, Mode=TwoWay, ValidatesOnDataErrors=True,NotifyOnValidationError=True, UpdateSourceTrigger=PropertyChanged}"
            materialDesign:HintAssist.Hint="{Binding Header, Mode=OneWay}"
            materialDesign:TextFieldAssist.TextBoxViewMargin="1 0 1 0"
            materialDesign:HintAssist.FloatingScale="0.85"
            materialDesign:ValidationAssist.UsePopup="False"
            HorizontalAlignment="Stretch" HorizontalContentAlignment="Center"
            Style="{Binding ValueTextBoxStyle, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:JobPropertyControl}}}" 
            IsReadOnly="{Binding IsReadOnly, Mode=OneWay}"/>

```

**Comment by RobSmyth** [comment]
As the issue persists with 3.2.0 should i / can I reopen the issue?

**Comment by RobSmyth** [comment]
Do closed issues get looked at?

**Comment by Keboo** [comment]
@RobSmyth are you able to provide a project that reproduces the issue?

**Comment by RobSmyth** [comment]
I'll see if I can, current code is in a relatively large project.

**Comment by CorradoBarbero** [comment]
@Keboo, I just realize now that you had closed the issue, while "not using the popup" is just a workaround, which worked and is fully acceptable for me but does not mean the defect is solved. Sorry if I failed to keep this on track.

@RobSmyth, I can prepare a sample in case you can't, just let me know.

**Comment by RobSmyth** [comment]
@CorradoBarbero - Trying to get to it. Not when/if I can.
